pipeline:
  backend:
    image: python
    commands:
      - echo test
      - pwd
      - ls /drone/src/build
    volumes:
      - name: build_cache
        path: /drone/src/build

volumes:
- name: build_cache
  host:
    path: /tmp/cache/futurewiz-rms/storage-api/build