pipeline:
  backend:
    image: python
    commands:
      - echo test
      - pwd
    
  push:
    image: plugins/docker
    settings:
      repo: dlwodnjs724/react-firebase-demo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    # tags: latest
    # repo: dlwodnjs724/react-firebase-demo
    # username: $DOCKER_USERNAME
    # password: $DOCKER_PASSWORD
    # secrets: [docker_username, docker_password]
