pipeline:
  backend:
    image: python
    commands:
      - echo test
      - pwd
    
  push:
    image: plugins/docker
    tag: latest
    repo: dlwodnjs724/react-firebase-demo
    secrets: [docker_username, docker_password]
